### ISSUE TITLE
[Discussion] Direction of this repo

### ISSUE THREAD

**Issue by raphdeknop** [pomber/awesome-word-pairs#4]
I found this repo via Twitter and find it interesting. 

I think the list can be longer than we expect and could serve as a 'reference'. Should we, however, only add the programming-related pairs ? I feel like we shouldn't because the definition of what  _is_ programming related can be quite fuzzy but I wanted your opinions.

**Comment by pomber** [comment]
Hi! Yes, the idea is to make it programming-related. Yes, it is fuzzy. If necessary, it can become less fuzzy using a metric like "amount of results in GH code search".

I saw your PR (thank you!), you have a lot of good pairs there (like "idle"/"busy"), others not very related (like "rural"/"urban").

I also want to keep it simple and only have a readme with the list. If you change it to add a subset of those pairs (using your judgment to choose the programming-related ones) to the readme I'll merge it.

**Comment by raphdeknop** [comment]
Stale issue
